server:
  port: 8080

spring:
  application:
    name: dymall-mbtt-service  # 添加应用程序名称
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource: # 数据库连接URL，记得数据库名称为“dymall”
    url: jdbc:mysql://localhost:3306/dymall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # 数据库用户名
    password: ${dy.db.pw} # 数据库密码，动态引用 `dy.db.pw`
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER  # 解决 Spring Boot 2.6+ Swagger 兼容问题
      throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  # Redis配置
  redis:
    host: localhost  # 修改为 localhost
    port: 16379     # 默认端口号
    password: simple29  # 根据需要设置密码
    database: 0        # Redis数据库的索引，默认是0
  # RabbitMQ配置
  rabbitmq:
    host: localhost         # 修改为 localhost
    port: 5672
    username: admin         # 生产环境建议修改
    password: admin         # 生产环境必须修改 RabbitMQ 密码
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual  # 手动确认消息
        prefetch: 100             # 每次处理100条消息
    publisher-confirm-type: correlated
    publisher-returns: true
    networks:
      - my-network
  # Elasticsearch配置
  data:
    elasticsearch:
      rest:
        uris: http://elasticsearch:9200  # 修改为 localhost
        connection-timeout: 10s
        read-timeout: 30s
      image: elasticsearch:7.17.14
      networks:
        - my-network
      environment:
        - network.host=0.0.0.0
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms512m -Xmx512m

mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.mbtt.service.domain.po
  type-handlers-package: cn.mbtt.service.handler  # 指定 TypeHandler 类所在包
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    cn:
      # 设置不同包的日志级别
      mbtt:
        mapper: debug  # `mapper` 包的日志级别为 debug，用于详细调试 SQL 操作
        service: info  # `service` 包的日志级别为 info，记录一般服务信息
        controller: info  # `controller` 包的日志级别为 info，记录请求信息
  pattern:
    dateformat: HH:mm:ss:SSS  # 日志日期格式，包含时分秒及毫秒
  file:
    path: "logs/${spring.application.name}"  # 日志文件存储路径，使用应用程序名称创建日志文件夹

knife4j:
  enable: true
  openapi:
    title: dymall商城接口文档
    description: "商城接口文档"
    email: axibong63@gmail.com
    name: axi
    version: v1.0.0
  group:
    default:
      group-name: default
      api-rule: package
      api-rule-resources:
        - cn.mbtt.service.controller

jwt:
  tokenHeader: Authorization  # JWT存储的请求头
  secret: dymall-secret       # JWT加解密使用的密钥
  expiration: 604800          # JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '        # JWT负载中拿到开头

secure:
  ignored:
    urls:  # 安全路径白名单
      - /doc.html
      - /webjars/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /v2/api-docs
      - /v3/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /product/**
      - /brand/**
      - /alipay/**
      - /test-db/
      - /login
      - /getVerifiCodeImage

alipay:
  # 支付宝应用 ID
  appId: 9021000145623399
  # 应用私钥
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCpAXbbhHXHvRj6mQwdH1utYUDJMd9MBBAptpkYccfaPiEcf9RnpRSbn1J3fOp06pnm6dTORZj3K77M+FDoeIUD9Y3mt9UcIJLIbO+EYEMuq/9bM9Qj9TTp47mRTdhOqBiGbjmMW9PtueKr9e0hnejVAFWNn9T7rXpoTXBalHLihFq92+srrT5teABfZjeUT4caMXECch54nmUrZb6Q+ozPHv4fAUq3RC34SNxgZQbXI7Gorby3gIk2kuujugRf9CkICaNEOoqERG99ptk6YxnP12r8t3O0hCCOnCXvOmdqgzNb3PQY7F+oaDy3uMdRfAkG9rekzUNbmhoSk2uKNJcHAgMBAAECggEAQdtiN5RcWSMk0rJE+Cw6C0v0dPJMM1D6A2c2LUJZQIApYvOlD2ZSq3ngJtO0gS7SHhtMY7zXKKoRRcoVrSEZpDtRunA0SSugRx28D/d69nrrnNyLdB+fKO0maKrO+YejVu8o2bsG0II5BA1nBEyGaEojDHcWBaTKKE7U01c5lW6fxRSM3D3VlIvxQz/mbjrP2Gv/pcuF9cgLJqCBcaZUUoEc/H42oEdK211Ccqbu6e1OboAa2dFjvUrEu26t0snD1FOjpDAZEeUA2PWxvwpjX84uOu3BxyRe8rEP4JiCJ2AFKfIedIT+TsutX/3NxyDjKMZTHpYtlzbn/TpiJK3CsQKBgQDWpmcKIjqHF8RfQ9MVhme4ePM/spFY7vCu/qv6jBjDgxunh+SK8rs6L66L+DXK2ebfNSpdROgVg6lbxCrTq/8A6hH7UtZBbcd3gmT90JHlSQNi2IMV5doOezabcjsoNzU690TnixZuJ2A5Zob6ZF59fWfb8j27V3jUgfSkeu6VgwKBgQDJkBXjvEtXswhQ+1Mzji8J9hHnmHZL1HrMiswCWTVeeEkxSKual79QBTp734UL53ZwIpJgK4+ikMjc0U+LJbefGrRu/Jn7o+4TP3T+bklkYXExK3E061UQV0fsbcvf/bFn3P4h2/hwSw+MrFLNf5A9bnpE9pzNOtZl+2pG1qhFLQKBgHcSWgh6EmOMYKfEFR1UsMbZeX61TQG7kpJQvhA/lSEn4rhdnv8hRZEykC4fI6ACnprlgDm7Fs+QeOtp96PyPoRAVHdJbYdgIY1/LQzLnZNGnHVBy/3iwsLTwOgcRwq5DXNHZdbYBjpW538QDAJsmSod3fZZ+7qn/GROLurrMtyHAoGAG8TrDx4Q7zsuKSIG+3JaTrAFFXguzBGw/V8d7jDmJmbCBrUxVzIS3G5r+Ub5KIOyEI7ixbcaqdXypmF76PrASn4+X5ATktSp5yL19luxZs/57UFD7nuBk6fCs/MIhIqKF3od1QJePvJIaSQQoFkzwRLoa3nibm/tu80gfjPyqN0CgYBgHQU2mdzyRMUUISk3zdcdJpCCmW6wqgu1lWna9FncpNPl6FbYBL5eErtAVikv/KgTPWL14XFEXpgwcz36mIgF9krugur+c33XQnaHtqT+UGUm2aBiS7xhmAxRy8UcGthDzEJCsPLJEg5CRhb9VEETfmsXie4QgPfpt/GdG8KUyw==
  # 支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiimIt3UQEnL/AT2x+iyrtuoJNpMwzzqVBApRyMYu5B50XyQMpFWLSpJq2atYAEjfIo9cpUXiycTHsdA8azZXHeQDnrVEzFJToGOfC7S1xvudewDMTosgERV/2tUuhbRBeO6kP4SqdlIjJDuNL1EjdYqCjM9OcDGW6Ij8jJForV4uWqFldgv4cd8aj1VR30TI9QlqZsk+JMzJivWllnFdsOUfX+vRxHZYFaD99cvfaC12RKRW8nAm38EUyz5/fNVc4TjVOhLWVHkbhkj/9PL6NikW01dX2wRTSaMCCUQTcsefxohHjjiYEufOd4xVOustQrQ0zC67sG4wa1V/TC9TKwIDAQAB
  # 回调接口地址（公网地址 + 接口 URI）
  notifyUrl:
